### ISSUE TITLE
Hash invalid issues.

### ISSUE THREAD

**Issue by gaycookie** [comp500/packwiz-installer#3]
Dear developer.

After reading this on the Packwiz repository: 
`To distribute a packwiz modpack, you'll first want to set up a web hosting service (such as Netlify, Github Pages, GitLab Pages) so that your pack files are accessible from a HTTP/HTTPS link.`.

I decided to try it out using Github Pages.
But I keep gettings errors with `Hash invalid!`, 
even though when I use the command `packwiz serve` on my local machine, all seems to work fine.

According to my git the files local and on my repository are the same and nothing has changed.
But whenever I try to use my `pack.toml` on my Github pages, it just keeps giving those errors.

Now I'm curious what am I doing wrong and or what can I do about this?
The repository I'm talking about can be found here: https://github.com/gaycookie/Fabricated
And the Github Page url can be found here: https://gaycookie.github.io/Fabricated/

Edit: The issues appear to only be on certain files
Errors can be found here: https://pastebin.ubuntu.com/p/TchNyfwbZC/

Thanks in advance.

**Comment by comp500** [comment]
This looks like a line ending conversion issue, if you're on Windows. See https://github.com/comp500/packwiz#usage-with-git

**Comment by gaycookie** [comment]
> This looks like a line ending conversion issue, if you're on Windows. See https://github.com/comp500/packwiz#usage-with-git

I feel so stupid that I completely read over that part, that did indeed help me with this problem!
I'm sorry I did not pay attention to the README.
